name = "dmlog-ai"
main = "worker/index.ts"
compatibility_date = "2025-03-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./web"

[[d1_databases]]
binding = "DB"
database_name = "dmlog-db"
database_id = "e102c3ea-0a04-43a2-9b6d-678d4db1a3c9"

[[kv_namespaces]]
binding = "KV"
id = "8975d85b10664167b4d84a531d32344d"

[vars]
ENVIRONMENT = "production"
THEME = "dmlog"
PERSONALITY = "dnd-dm"
