name = "reallog-ai"
account_id = "049ff5e84ecf636b53b162cbb580aae6"
main = "src/worker.ts"
compatibility_date = "2024-12-01"

[[kv_namespaces]]
binding = "REALLOG_KV"
id = "a024a850d3f74543abb9475ed703517c"
